version: '3'
services:
  postgres:
    image: postgres:latest
    container_name: postgres-container
    environment:
      POSTGRES_USER: milica
      POSTGRES_PASSWORD: milica
      POSTGRES_DB: tasks_db
    ports:
      - "5432:5432"  

  golang-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: golang-app-container
    depends_on:
      - postgres
    environment:
      DATABASE_HOST: postgres
      DATABASE_PORT: 5432
      DATABASE_USER: milica
      DATABASE_PASSWORD: milica
      DATABASE_NAME: tasks_db
    ports:
      - "8080:8080"  # Map your Go application port to host
